#!/usr/bin/env bash
AXIOM_PATH="$HOME/.axiom"

download=false

for var in "$@"
do
    if [ $var == "--download" ]
    then
        download=true
    fi
done

if [ -z "$1" ]
then
    ans="$(doctl compute droplet list | awk '{ print $2 }' | grep -v "Name" | fzf)"
    ip="$(doctl compute droplet list | grep "$ans" | awk '{ print $3 }')"
    scp -P2266 op@"$ip":/home/op/vpn/client.ovpn /tmp/"$ans".ovpn
    sudo openvpn /tmp/"$ans".ovpn
else
    if [ $download ]
    then
        ans="$(doctl compute droplet list | awk '{ print $2 }' | grep -v "Name" | fzf)"
        ip="$(doctl compute droplet list | grep "$ans" | awk '{ print $3 }')"
        scp -P2266 op@"$ip":/home/op/vpn/client.ovpn /tmp/"$ans".ovpn
        cp /tmp/"$ans".ovpn $AXIOM_PATH/current-config.ovpn
    else
        ip="$(doctl compute droplet list | grep "$1" | awk '{ print $3 }')"
        scp -P2266 op@"$ip:"/home/op/vpn/client.ovpn /tmp/"$1".ovpn
        sudo openvpn /tmp/"$1".ovpn
    fi
fi
